#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License. See accompanying LICENSE file.
#
baseurl = "https://kyuubi.apache.org"
title = "Apache Kyuubi"
copyright = "Copyright © 2021-{year}"
enableEmoji = true
footnotereturnlinkcontents = "<sup>^</sup>"
uglyurls = true
googleAnalytics = "UA-7453027-1"
contentDir = "src"
publishDir = "content"

[[menu.main]]
  name = "Download"
  url = "releases.html"
  weight = 1


[[menu.main]]
  name = "Documentation"
  identifier = "documentation"
  weight = 2

[[menu.main]]
   name = "Latest"
   parent = "documentation"
   url = "docs/latest/index.html"
   weight = 1

[[menu.main]]
   name = "Master(unreleased)"
   parent = "documentation"
   url = "https://kyuubi.readthedocs.io/en/latest/index.html"
   weight = 10

[[menu.main]]
   name = "Community"
   identifier = "community"
   weight = 3

[[menu.main]]
   name = "Code of Conduct"
   url = "https://www.apache.org/foundation/policies/conduct"
   parent = "community"
   weight = 1

[[menu.main]]
   name = "Development"
   identifier = "development"
   weight = 4

[[menu.main]]
   name = "Github"
   identifier = "github"
   url = "https://github.com/apache/incubator-kyuubi"
   weight = 5

[[menu.main]]
   name = "ASF"
   identifier = "asf"
   weight = 6

[[menu.main]]
   name = "Foundation"
   url = "https://www.apache.org/"
   parent = "asf"

[[menu.main]]
   name = "License"
   url = "https://www.apache.org/licenses/"
   parent = "asf"

[[menu.main]]
   name = "Events"
   url = "https://www.apache.org/events/current-event"
   parent = "asf"

[[menu.main]]
   name = "Security"
   url = "https://www.apache.org/security/"
   parent = "asf"

[[menu.main]]
   name = "Sponsorship"
   url = "https://www.apache.org/foundation/sponsorship.html"
   parent = "asf"

[[menu.main]]
   name = "Thanks"
   url = "https://www.apache.org/foundation/thanks.html"
   parent = "asf"


# Configure the English version of the website.
[languages.en]
  languageCode = "en-us"

[markup]
  defaultMarkdownHandler = 'goldmark'
  [markup.asciidocExt]
    backend = 'html5'
    extensions = []
    failureLevel = 'fatal'
    noHeaderOrFooter = true
    preserveTOC = false
    safeMode = 'unsafe'
    sectionNumbers = false
    trace = false
    verbose = false
    workingFolderCurrent = false
    [markup.asciidocExt.attributes]
  [markup.blackFriday]
    angledQuotes = false
    footnoteAnchorPrefix = ''
    footnoteReturnLinkContents = ''
    fractions = true
    hrefTargetBlank = false
    latexDashes = true
    nofollowLinks = false
    noreferrerLinks = false
    plainIDAnchors = true
    skipHTML = false
    smartDashes = true
    smartypants = true
    smartypantsQuotesNBSP = false
    taskLists = true
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
      goldmark-emoji = true
    [markup.goldmark.parser]
      autoHeadingID = true
      autoHeadingIDType = 'github'
      [markup.goldmark.parser.attribute]
        block = false
        title = true
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'monokai'
    tabWidth = 4
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2


# Configure minify.
[minify]
  [minify.tdewolff.html]
    keepQuotes = true
