name: Deploy ASF site

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 0.136.4
          extended: true
      - name: Build
        run: hugo --minify
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: asf-site
          publish_dir: content
          destination_dir: content
          force_orphan: true
      - run: |
          git config --global user.name  "GitHub Actions"
          git config --global user.email "dev@kyuubi.apache.org"
          git fetch --all
          git checkout asf-site
          echo 'publish:'           >> .asf.yaml
          echo '  whoami: asf-site' >> .asf.yaml
          git add .asf.yaml
          git commit -m '.asf.yaml'
          git push origin asf-site
